In [1]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

data = asarray([['bronze'], ['silver'], ['gold']])
print (data)

encoder = OrdinalEncoder()

result = encoder.fit_transform(data)
print(result)

[['bronze']
 ['silver']
 ['gold']]
[[0.]
 [2.]
 [1.]]


In [2]:
!pip install category_encoders

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 48.5 MB/s eta 0:00:0000:010:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.9/233.9 kB 27.1 MB/s eta 0:00:00


In [7]:
import pandas as pd
import numpy as np
from pandas import DataFrame
df = pd.DataFrame({'Award':['Bronze', 'Silver', 'Gold']})
print(df)

    Award
0  Bronze
1  Silver
2    Gold


In [16]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red'],['green'], ['blue']])
print(data)

encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [5]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red'],['green'], ['blue']])
print(data)

encoder = OneHotEncoder(drop='first',sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 1.]
 [1. 0.]
 [0. 0.]]


In [20]:
# Encoding categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
